apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-gvbl
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0066-tenant/tkrw-pr712-0075-0066-app/devfile-sample-gvbl@sha256:3213a0dbe757ceedce6791cc281e54b2cc56dc8156439da940f6d4f500e711a1
        name: my-nodejs
        resources: {}
status: {}
